global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using PerformanceTester.IntegrationTesting;
global using PerformanceTester.Reporting;
global using Xunit;
global using Xunit.Abstractions;
