using System.Text.Json;
using System.Text.RegularExpressions;
using PerformanceTester.Reporting.ChartGeneration;
using PerformanceTester.Reporting.IntegrationTests.Builders;
using PerformanceTester.Reporting.IntegrationTests.Infrastructure;
using Xunit;
using Xunit.Abstractions;

namespace PerformanceTester.Reporting.IntegrationTests;

/// <summary>
/// Integration tests for IReportGenerator (JSON report generation).
/// Tests verify report generation matches Python implementation output.
/// </summary>
public sealed class ReportGeneratorTests : IntegrationTest
{
    public ReportGeneratorTests(ITestOutputHelper output) : base(output)
    {
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldCreateAllSevenFiles()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testReport = new TestReportBuilder()
            .WithProcessName("goReferenceService")
            .WithTestDate(new DateTime(2025, 11, 13, 14, 25, 30, DateTimeKind.Utc))
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert
            var files = Directory.GetFiles(outputDirectory);
            Assert.Equal(7, files.Length); // 7 JSON files (PNG chart is generated by ChartGenerator)

            // Expected file naming pattern
            var timestamp = testReport.TestDate.ToString("yyyyMMdd_HHmmss");
            var sanitizedName = "goreferenceservice"; // After sanitization

            var expectedFiles = new[]
            {
                $"test-report-{timestamp}-{sanitizedName}.json",
                $"test-report-{timestamp}-{sanitizedName}.events-throughput.json",
                $"test-report-{timestamp}-{sanitizedName}.api-throughput.json",
                $"test-report-{timestamp}-{sanitizedName}.resource-metrics.json",
                $"test-report-{timestamp}-{sanitizedName}.system-metrics.json",
                $"test-report-{timestamp}-{sanitizedName}.rabbitmq-metrics.json",
                $"test-report-{timestamp}-{sanitizedName}.postgres-metrics.json"
            };

            foreach (var expectedFile in expectedFiles)
            {
                var fullPath = Path.Combine(outputDirectory, expectedFile);
                Assert.True(File.Exists(fullPath), $"Expected file not found: {expectedFile}");
            }
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldUseCorrectDecimalPrecision()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        
        // Create test report with specific decimal precision values
        var phaseTimestamps = new PhaseTimestamps
        {
            Phase1Start = 0.0,
            Phase1End = 5.333,
            Phase2Start = 5.333,
            Phase2End = 44.556,
            Phase3Start = 45.000,
            Phase3End = 75.333
        };

        var results = new TestResults
        {
            Phase1Publish = new PublishResults
            {
                DurationSeconds = 5.333,
                ThroughputEventsPerSec = 1875.22  // 2 decimals
            },
            Phase2Consume = new ConsumeResults
            {
                DurationSeconds = 39.223,
                ThroughputEventsPerSec = 254.98
            },
            Phase3Api = new ApiResults
            {
                DurationSeconds = 30.333,
                TotalRequests = 3245,
                ThroughputCallsPerSec = 107.00,
                SuccessCount = 3245,
                SuccessPercentage = 100.0,  // 1 decimal
                ErrorCount = 0,
                ErrorPercentage = 0.0
            }
        };

        var testReport = new TestReportBuilder()
            .WithRuntime(125.456)  // 3 decimals
            .WithPhaseTimestamps(phaseTimestamps)
            .WithResults(results)
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert - Read main report
            var mainReportPath = Directory.GetFiles(outputDirectory, "*testservice.json").First();
            var json = await File.ReadAllTextAsync(mainReportPath);
            var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            // Time in seconds: 3 decimals
            var totalRuntime = root.GetProperty("total_runtime_seconds").GetDouble();
            Assert.Equal(125.456, totalRuntime);

            // Throughput (per sec): 2 decimals
            var publishThroughput = root.GetProperty("results")
                .GetProperty("phase1_publish")
                .GetProperty("throughput_events_per_sec")
                .GetDouble();
            Assert.Equal(1875.22, publishThroughput);

            // Percentage: 1 decimal
            var successPercentage = root.GetProperty("results")
                .GetProperty("phase3_api")
                .GetProperty("success_percentage")
                .GetDouble();
            Assert.Equal(100.0, successPercentage);
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Theory]
    [InlineData("java21SpringBootGraalReferenceService", "java21springbootgraalreferenceservice")]
    [InlineData("dotnet9AotReferenceService.exe", "dotnet9aotreferenceservice")]
    [InlineData("python ReferenceService", "python-referenceservice")]
    [InlineData("go-reference-service.dll", "go-reference-service")]
    [InlineData("rust__service--test.jar", "rust-service-test")]
    public async Task GenerateReportAsync_ShouldSanitizeProcessName(string inputName, string expectedSanitized)
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testReport = new TestReportBuilder()
            .WithProcessName(inputName)
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert - Check that files use sanitized name
            var files = Directory.GetFiles(outputDirectory, "*.json");
            Assert.All(files, file =>
            {
                var filename = Path.GetFileName(file);
                Assert.Contains(expectedSanitized, filename);
            });
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldUseSnakeCasePropertyNames()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testReport = new TestReportBuilder()
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert - Read main report
            var mainReportPath = Directory.GetFiles(outputDirectory, "*testservice.json").First();
            var json = await File.ReadAllTextAsync(mainReportPath);

            // Check for snake_case properties (should exist)
            Assert.Contains("\"test_date\"", json);
            Assert.Contains("\"total_runtime_seconds\"", json);
            Assert.Contains("\"phase_timestamps\"", json);
            Assert.Contains("\"monitored_process\"", json);
            Assert.Contains("\"throughput_events_per_sec\"", json);

            // Check for camelCase properties (should NOT exist)
            Assert.DoesNotContain("\"testDate\"", json);
            Assert.DoesNotContain("\"totalRuntimeSeconds\"", json);
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldFormatTimestampsCorrectly()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testDate = new DateTime(2025, 11, 13, 14, 25, 30, DateTimeKind.Utc);
        var testReport = new TestReportBuilder()
            .WithTestDate(testDate)
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert - Main report timestamp format
            var mainReportPath = Directory.GetFiles(outputDirectory, "*testservice.json").First();
            var json = await File.ReadAllTextAsync(mainReportPath);
            var doc = JsonDocument.Parse(json);

            var testDateString = doc.RootElement.GetProperty("test_date").GetString();
            Assert.Equal("2025-11-13 14:25:30", testDateString);

            // Assert - Sample timestamp format (ISO 8601 with timezone)
            var eventsThroughputPath = Directory.GetFiles(outputDirectory, "*.events-throughput.json").First();
            json = await File.ReadAllTextAsync(eventsThroughputPath);
            doc = JsonDocument.Parse(json);

            var samples = doc.RootElement.GetProperty("samples");
            if (samples.GetArrayLength() > 0)
            {
                var firstSample = samples[0];
                var sampleTimestamp = firstSample.GetProperty("timestamp").GetString();

                // Format: "2025-11-13T14:25:30.100000" (ISO 8601 without timezone per Python contract)
                Assert.Matches(@"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}$", sampleTimestamp!);
            }
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldCalculateStatisticsCorrectly()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testDate = new DateTime(2025, 11, 13, 14, 25, 30, DateTimeKind.Utc);
        var testReport = new TestReportBuilder()
            .WithTestDate(testDate)
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .WithEventsThroughputSamples(ThroughputMetricSampleBuilder.CreateWithKnownStatistics(testDate))
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert
            var eventsThroughputPath = Directory.GetFiles(outputDirectory, "*.events-throughput.json").First();
            var json = await File.ReadAllTextAsync(eventsThroughputPath);
            var doc = JsonDocument.Parse(json);
            var summary = doc.RootElement.GetProperty("summary");

            // Verify calculations (known statistics: avg=100, peak=150, min=50)
            var avgRate = summary.GetProperty("avg_events_per_second").GetDouble();
            Assert.Equal(100.00, avgRate, precision: 2);

            var peakRate = summary.GetProperty("peak_events_per_second").GetDouble();
            Assert.Equal(150.00, peakRate, precision: 2);

            var minRate = summary.GetProperty("min_events_per_second").GetDouble();
            Assert.Equal(50.00, minRate, precision: 2);
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldExcludeZerosFromMinCalculation()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testDate = new DateTime(2025, 11, 13, 14, 25, 30, DateTimeKind.Utc);
        var testReport = new TestReportBuilder()
            .WithTestDate(testDate)
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .WithEventsThroughputSamples(ThroughputMetricSampleBuilder.CreateWithZeros(testDate))
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert
            var eventsThroughputPath = Directory.GetFiles(outputDirectory, "*.events-throughput.json").First();
            var json = await File.ReadAllTextAsync(eventsThroughputPath);
            var doc = JsonDocument.Parse(json);
            var summary = doc.RootElement.GetProperty("summary");

            // Min should exclude zeros (values: 100, 150, 0, 75, 0, 50 → min=50)
            var minRate = summary.GetProperty("min_events_per_second").GetDouble();
            Assert.Equal(50.0, minRate, precision: 2);

            // Average should include zeros
            var avgRate = summary.GetProperty("avg_events_per_second").GetDouble();
            var expectedAvg = (100.0 + 150.0 + 0.0 + 75.0 + 0.0 + 50.0) / 6.0;
            Assert.Equal(expectedAvg, avgRate, precision: 2);
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldUseCorrectSamplingIntervals()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testReport = new TestReportBuilder()
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert - Events throughput: 100ms
            var eventsThroughputPath = Directory.GetFiles(outputDirectory, "*.events-throughput.json").First();
            var json = await File.ReadAllTextAsync(eventsThroughputPath);
            var doc = JsonDocument.Parse(json);
            var samplingInterval = doc.RootElement.GetProperty("sampling_interval_ms").GetInt32();
            Assert.Equal(100, samplingInterval);

            // Assert - Process resources: 500ms
            var resourceMetricsPath = Directory.GetFiles(outputDirectory, "*.resource-metrics.json").First();
            json = await File.ReadAllTextAsync(resourceMetricsPath);
            doc = JsonDocument.Parse(json);
            samplingInterval = doc.RootElement.GetProperty("sampling_interval_ms").GetInt32();
            Assert.Equal(500, samplingInterval);

            // Assert - RabbitMQ metrics: no sampling_interval_ms (event-driven from Docker)
            var rabbitmqMetricsPath = Directory.GetFiles(outputDirectory, "*.rabbitmq-metrics.json").First();
            json = await File.ReadAllTextAsync(rabbitmqMetricsPath);
            doc = JsonDocument.Parse(json);
            Assert.False(doc.RootElement.TryGetProperty("sampling_interval_ms", out _));
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldDifferentiateBetweenProcessAndContainerMetrics()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testReport = new TestReportBuilder()
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert - Process metrics use "memory_rss_mb" and include "threads"
            var resourceMetricsPath = Directory.GetFiles(outputDirectory, "*.resource-metrics.json").First();
            var json = await File.ReadAllTextAsync(resourceMetricsPath);
            var doc = JsonDocument.Parse(json);
            var samples = doc.RootElement.GetProperty("samples");

            if (samples.GetArrayLength() > 0)
            {
                var firstSample = samples[0];
                Assert.True(firstSample.TryGetProperty("memory_rss_mb", out _));
                Assert.True(firstSample.TryGetProperty("threads", out _));
                Assert.False(firstSample.TryGetProperty("memory_mb", out _));
            }

            // Assert - Container metrics use "memory_mb" and NO threads
            var rabbitmqMetricsPath = Directory.GetFiles(outputDirectory, "*.rabbitmq-metrics.json").First();
            json = await File.ReadAllTextAsync(rabbitmqMetricsPath);
            doc = JsonDocument.Parse(json);
            samples = doc.RootElement.GetProperty("samples");

            if (samples.GetArrayLength() > 0)
            {
                var firstSample = samples[0];
                Assert.True(firstSample.TryGetProperty("memory_mb", out _));
                Assert.False(firstSample.TryGetProperty("threads", out _));
                Assert.False(firstSample.TryGetProperty("memory_rss_mb", out _));
            }
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    [Fact]
    public async Task GenerateReportAsync_ShouldUseTwoSpaceIndentation()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("report-test");
        var testReport = new TestReportBuilder()
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();

        try
        {
            // Act
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Assert
            var mainReportPath = Directory.GetFiles(outputDirectory, "*testservice.json").First();
            var json = await File.ReadAllTextAsync(mainReportPath);

            var lines = json.Split('\n');

            // Check for 2-space indentation patterns
            Assert.Contains(lines, line => line.StartsWith("  \"test_date\""));
            Assert.Contains(lines, line => line.StartsWith("    \"phase1_start\""));

            // Verify NO tabs
            Assert.DoesNotContain("\t", json);
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }

    /// <summary>
    /// End-to-end integration test that ensures ReportGenerator and ChartGenerator work together.
    /// This test uses the production code path to catch any mismatches between what's written and what's read.
    /// Prevents regression of the memory_rss_mb vs memory_mb bug.
    /// </summary>
    [Fact]
    public async Task ReportGenerator_And_ChartGenerator_ShouldWorkTogether_RoundTripTest()
    {
        // Arrange
        var outputDirectory = System.FileSystem.CreateTempDirectory("roundtrip-test");
        var testReport = new TestReportBuilder()
            .WithSystemInfo(SystemInfoBuilder.CreateIntelI9())
            .Build();  // Use defaults - includes all required sample types

        try
        {
            // Act - Step 1: Generate all JSON reports using production ReportGenerator
            await System.Reporting.ReportGenerator.GenerateReportAsync(outputDirectory, testReport);

            // Act - Step 2: Generate chart using production ChartGenerator (reads the JSON files)
            var timestamp = testReport.TestDate.ToString("yyyyMMdd_HHmmss");
            var sanitizedName = testReport.MonitoredProcess.Name.ToLowerInvariant();
            var chartPath = Path.Combine(outputDirectory, $"test-report-{timestamp}-{sanitizedName}.chart.png");
            
            await ChartGenerator.GenerateChartAsync(chartPath, testReport, System.Reporting.Logger);

            // Assert - Verify chart was created successfully
            Assert.True(File.Exists(chartPath), "Chart PNG file should exist after round-trip");

            // Assert - Verify chart has reasonable size (not empty, not corrupted)
            var fileInfo = new FileInfo(chartPath);
            Assert.True(fileInfo.Length > 10_000, 
                $"Chart file should be > 10KB (actual: {fileInfo.Length} bytes)");
            Assert.True(fileInfo.Length < 5_000_000,
                $"Chart file should be < 5MB (actual: {fileInfo.Length} bytes)");

            // Assert - Verify all expected JSON files were created
            var jsonFiles = Directory.GetFiles(outputDirectory, "*.json");
            Assert.Equal(7, jsonFiles.Length); // Main + 6 metric files

            // Assert - Verify process resource metrics have correct structure (memory_rss_mb + threads)
            var resourceMetricsPath = Directory.GetFiles(outputDirectory, "*.resource-metrics.json").First();
            var resourceJson = await File.ReadAllTextAsync(resourceMetricsPath);
            var resourceDoc = JsonDocument.Parse(resourceJson);
            var samples = resourceDoc.RootElement.GetProperty("samples");
            
            if (samples.GetArrayLength() > 0)
            {
                var firstSample = samples[0];
                Assert.True(firstSample.TryGetProperty("memory_rss_mb", out _), 
                    "Process metrics should have memory_rss_mb");
                Assert.True(firstSample.TryGetProperty("threads", out _),
                    "Process metrics should have threads");
                Assert.False(firstSample.TryGetProperty("memory_mb", out _),
                    "Process metrics should NOT have memory_mb (should be memory_rss_mb)");
            }

            Output.WriteLine("✓ Round-trip test passed: ReportGenerator → ChartGenerator integration verified");
            Output.WriteLine($"  Chart created: {chartPath}");
            Output.WriteLine($"  Chart size: {fileInfo.Length:N0} bytes");
        }
        finally
        {
            System.FileSystem.CleanupTempDirectory(outputDirectory);
        }
    }
}
