<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PerformanceTester.Orchestration.IntegrationTests" />
    <InternalsVisibleTo Include="performance-tester" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PerformanceTester.Infrastructure\PerformanceTester.Infrastructure.csproj" />
    <ProjectReference Include="..\PerformanceTester.EventPublishing\PerformanceTester.EventPublishing.csproj" />
    <ProjectReference Include="..\PerformanceTester.EventConsuming\PerformanceTester.EventConsuming.csproj" />
    <ProjectReference Include="..\PerformanceTester.ProcessMonitoring\PerformanceTester.ProcessMonitoring.csproj" />
    <ProjectReference Include="..\PerformanceTester.DockerMonitoring\PerformanceTester.DockerMonitoring.csproj" />
    <ProjectReference Include="..\PerformanceTester.ApiLoadTesting\PerformanceTester.ApiLoadTesting.csproj" />
    <ProjectReference Include="..\PerformanceTester.Reporting\PerformanceTester.Reporting.csproj" />
    <ProjectReference Include="..\PerformanceTester.SystemMonitoring\PerformanceTester.SystemMonitoring.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dunet" Version="1.11.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PerformanceTester.Functional\PerformanceTester.Functional.csproj" />
  </ItemGroup>

</Project>
