package com.joancomasfdz.performancetest;

import jakarta.persistence.*;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.Instant;

/**
 * JPA entity representing an instrument status change event.
 * This entity stores the history of all status transitions for instruments,
 * allowing tracking of device state changes over time.
 *
 * @author Performance Test 2025
 * @version 1.0
 */
@Entity
@Table(name = "java21springbootgraal_instrument_status", indexes = {
    @Index(name = "idx_sb_graal_timestamp", columnList = "timestamp")
})
class InstrumentStatus {

    /**
     * Primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Unique identifier of the instrument/device.
     */
    @Column(name = "device_id", nullable = false)
    private String deviceId;

    /**
     * The status the instrument was in before this change.
     */
    @Column(name = "previous_status", nullable = false)
    private String previousStatus;

    /**
     * The status the instrument transitioned to.
     */
    @Column(name = "current_status", nullable = false)
    private String currentStatus;

    /**
     * Timestamp when this status change was recorded.
     */
    @Column(nullable = false)
    private Instant timestamp;

    /**
     * Default constructor required by JPA.
     */
    public InstrumentStatus() {
    }

    /**
     * Constructs a new instrument status record.
     *
     * @param deviceId the unique identifier of the device
     * @param previousStatus the previous status of the device
     * @param currentStatus the current status of the device
     * @param timestamp when the status change occurred
     */
    public InstrumentStatus(String deviceId, String previousStatus, String currentStatus, Instant timestamp) {
        this.deviceId = deviceId;
        this.previousStatus = previousStatus;
        this.currentStatus = currentStatus;
        this.timestamp = timestamp;
    }

    /**
     * Gets the primary key ID.
     *
     * @return the database-generated ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * Gets the device identifier.
     *
     * @return the unique identifier of the device
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the device identifier.
     *
     * @param deviceId the unique identifier of the device
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Gets the previous status.
     *
     * @return the status before this change
     */
    public String getPreviousStatus() {
        return previousStatus;
    }

    /**
     * Sets the previous status.
     *
     * @param previousStatus the status before this change
     */
    public void setPreviousStatus(String previousStatus) {
        this.previousStatus = previousStatus;
    }

    /**
     * Gets the current status.
     *
     * @return the status after this change
     */
    public String getCurrentStatus() {
        return currentStatus;
    }

    /**
     * Sets the current status.
     *
     * @param currentStatus the status after this change
     */
    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    /**
     * Gets the timestamp of this status change.
     *
     * @return when the status change was recorded
     */
    public Instant getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the timestamp of this status change.
     *
     * @param timestamp when the status change was recorded
     */
    public void setTimestamp(Instant timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        InstrumentStatus that = (InstrumentStatus) o;
        if (id != null && that.id != null) {
            return id.equals(that.id);
        }
        return deviceId != null && deviceId.equals(that.deviceId) &&
               timestamp != null && timestamp.equals(that.timestamp);
    }

    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        }
        int result = deviceId != null ? deviceId.hashCode() : 0;
        result = 31 * result + (timestamp != null ? timestamp.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "InstrumentStatus{" +
                "id=" + id +
                ", deviceId='" + deviceId + '\'' +
                ", previousStatus='" + previousStatus + '\'' +
                ", currentStatus='" + currentStatus + '\'' +
                ", timestamp=" + timestamp +
                '}';
    }
}

/**
 * Spring Data JPA repository for {@link InstrumentStatus} entities.
 * Provides standard CRUD operations and custom query methods.
 *
 * <p>Note: This interface is package-private because it's defined in the same file
 * as the InstrumentStatus entity class. This is acceptable for Spring Data JPA repositories.</p>
 *
 * @author Performance Test 2025
 * @version 1.0
 */
@Repository
interface InstrumentStatusRepository extends JpaRepository<InstrumentStatus, Integer> {

    /**
     * Finds the most recent instrument status record based on timestamp.
     *
     * @return the latest instrument status, or null if no records exist
     */
    InstrumentStatus findFirstByOrderByTimestampDesc();
}
